fidelity
{
Noun: Faithfulness to a person, cause, or belief, demonstrated by continuing loyalty and support.
}
fin
{
Noun: A flattened appendage on various parts of the body of many aquatic vertebrates and some invertebrates, including fish and cetaceans, used for propelling, steering, and balancing.
}
finch
{
Noun: A seed-eating songbird that typicaly has a stout bill and colorful plumage.
}
plumage
fitness
{
Noun:The condition of being physically fit and healthy.
}
flagellum
{
Noun: A slender threadlike structure, esp. a microscopic whiplike appendage that enables many protozoa, bacteria, spermatozoa, etc.,to swim.
}
flake
{
Verb:Lay(a rope)in loose coils in order to prevent it from tanglint. 
Noun:A rack or shelf for storing or drying food such as fish. A small, flat, thin piece of something, typically one that has broken away or been peeled off from a larger piece.
}
flame
{
Noun: A hot glowing body of ignited gas that is generated by something on fire. 
Verb:Burn and give off flames. Set(something)alight.
}
flask
{
Noun:A container or bottle, in particular. A narrow-necked glass container.
}
flavoring
{
Noun:A substance used to give a different, stronger, or more agreeable test to food or drink.
}
flint
{
Noun:A hard gray rock consisting of nearly pure chert, occurring chiefly as nodules in chalk.
}
flock
{
Verb:Congregate or mass in a flock or large group. 
Noun:A number of birds of one kind feeding, resting, or traveling together.
}
flora
{
Noun:The plant of a particular region, habitat, or geological period. fauna.
}
flourish
{
Noun:A bold or extravagant gesture or action, made esp.to attract the attention of others. 
Verb:(of a person, animal, or other living organism)Grow or develop in a healthy or vigorous way, esp. as the result of a particularly favorable environment.
}
fluctuate
{
Verb: Rise and fall irregularly in number or amount.
}
flux
{
Noun: The action or process of flowing or flowing out. 
Verb: Treat(a metal object)with a flux to promote melting.
}
fold
{
Verb:Shut(livestock)in a fold. 
Noun:A pen or enclosure in a field where livestock, esp. sheep, can be kept.
}
foliage
folklore
{
Noun: The traditional beliefs, customs, and stories of a community, passed through the generations by word or mouth.
}
foment
{
Verb: Instigate or stir up(an undesirable or violent sentiment or course of action).
}
forage
{
Verb:(of a person or animal)Search widely for food or provisions. Obtain.
}
forefront
{
Noun:the leading or most important position or place.
}
foreshorten
{
Verb:Portray or show(an object or view)as closer than it is or as having less depth or distance, as an effect of perspective or the angle of vision.
}
formidable
{
Adjective:Inspiring fear or respect through being impressively large, powerful, intence, or capable.
}
formulate
{
Verb:Create or devise methodically(a strategy or a proposal).
}
fort
{
Noun: A fortified building or strategic position.
}
fortuitous
{
Adjective: Happening by accident or chance rather than design.
}
fossil
{
Noun: The remains or impression of a prehistoric organism preserved in petrified form or as a mold or cast in rock.
}
foster
{
Verb: Encourage or promote the development of(something, typically something regarded as good).Bring up(a child that is not one's own by birth). 
Adjective: Denoting someone that has a specified family connection through fostering rather than birth.
}
fountain
{
Noun: a structure from which water is pumped up into the air, found as an ornament in parks and gardens/yards.
}
portion
{
Verb:Divide(something)into shares to be distributed among two or more people. 
Noun:A part of a whole; an amount, section, or piece of something.
}
fraction
{
Noun:A numerical quantity that is not a whole number.
}
fracture
{
Verb: Break or cause to break. 
Noun: The cracking or breaking of a hard object or material.
}
fragment
{
Noun: A small part broken or separated off something. An isolated or incomplete part of something. 
Verb: Break or cause to break into fragments.
}
fragrant
{
Adjective: Having a pleasant or sweet smell.
}
fray
{
Verb:(of a fabric, rope, or cord)Unravel or become worn at the edge, typically through constant rubbing. 
Noun: a battle of fight.
}
freight
{
Verb:Transport(goods)in bulk by truck, train, ship, or aircraft. 
Noun:Goods transported by truck, train, ship, or aircraft.
}
frenzy
{
Noun:A state of period of uncontrolled excitement or wild behavior.
}
fresco
{
Verb: Paint in fresco. 
Noun: A painting done rapidly in watercolor on wet plaster on a wall or ceiling, so that the colors penetrate the plaster and become fixed as it dries.
}
friction
{
Noun:Conflict or animosity caused by a clash of wills, temperaments, or opinions.
}
frigid
{
Adjective: Very cold in temperature. (esp. of a woman)Unable or unwilling to be sexually aroused and responsive.
}
frost
{
Verb: Cover(something)with or as if with small ice crystals; freeze. 
Noun: A deposit of small white ice crystals fromed on the ground or other surfaces when the temperature falls below freezing.
}
frugal
{
Adjective: Sparing or economical with regard to money or food. Simple and plain and costing little.
}
fungus
{
Noun:Any of a group of unicellular, multicellular, or syncytial spore-producing organisms feeding on organic matter, including molds, yeast, mushrooms, and toadstools. Used to describe something that has appeared or grown rapidly and is considered unpleasant or unattractive.
}
furnace
{
Noun:An enclosed structure in which material can be heated to very high temperatures, e.g., for smelting metals.
}
furnish
{
Verb: Provide(a house or room)with furniture and fittings. Supply someone with(something); give(something)to someone.
}
fuse
{
Verb:Join or blend to form a single entity. Provide(a circuit or electrical applicance) with a fuse. 
Noun:A length of material along which a small flame moves to explode a bomb or firework, meanwhile allowing time for those who light it to move to a safe distance.
}
galaxy
{
Noun: A system of millions or billions of stars, together with gas and dust, held together by gravitational attraction.
}
gallery
{
Noun: A room or building for the display or sale of works of art. A collection of pictures.
}
gallop
{
Noun:A ride on a horse at this pace. 
Verb:(of a horse)Go at the pace of a gallop.
}
gaseous
{
Adjective:Of, relating to, or having the characteristics of a gas.
}
gasoline
{
Noun:Refined petroleum used as fuel for internal combustion engines.
}
gear
{
Verb: Design or adjust the gears in (a machine)to give a specified speed or power output. Adjust or adapt something to suit a special purpose or need. 
Noun: Equipment that is used for a particular purpose.
}
gem
{
Noun: A precious or semiprecious stone, esp. when cut and polished or engraved.
}
gemstone
{
Noun: A precious or semiprecious stone, esp. one cut, polished, and used in a piece of jewelry.
}
gender
//unfamiliar
finch
plumage
flagellum
flask
flock
fluctuate
formidable
fortuitous
fracture
frenzy
frigid
frugal
gear
foment
fragrant
